### ISSUE TITLE
Compiling on OS/X fails with fatal error: 'ranges' file not found

### ISSUE THREAD

**Issue by david0** [Dougal-s/Aether#5]
Hi,
I'm trying to compile on OS/X 10.15.7 with AppleClang 12.0.0.12000032.

Unfortunately ranges do not seem to be available:
```
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ -DNDEBUG -Daether_dsp_EXPORTS  -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -fPIC -fvisibility=hidden -Wall -Wextra -Wpedantic -Wshadow -Weffc++ -Wstrict-aliasing -Wunreachable-code -Wdouble-promotion -Werror -Wconversion -Wsign-conversion -O3 -std=c++2a -MD -MT CMakeFiles/aether_dsp.dir/src/DSP/aether_dsp.cpp.o -MF CMakeFiles/aether_dsp.dir/src/DSP/aether_dsp.cpp.o.d -o CMakeFiles/aether_dsp.dir/src/DSP/aether_dsp.cpp.o -c /tmp/aether-20210420-84893-gx3oq1/src/DSP/aether_dsp.cpp
In file included from /tmp/aether-20210420-84893-gx3oq1/src/DSP/aether_dsp_lv2.cpp:16:
In file included from /tmp/aether-20210420-84893-gx3oq1/src/DSP/aether_dsp.hpp:14:
/tmp/aether-20210420-84893-gx3oq1/src/DSP/utils/random.hpp:7:10: fatal error: 'ranges' file not found
```

Looking at https://en.cppreference.com/w/cpp/compiler_support "The One Ranges Proposal" looks like no Apple Clang is supporting that :-(

**Comment by REIS0** [comment]
I got the same error compiling in Pop_OS! 20.04

```
  6%] Building CXX object CMakeFiles/aether_dsp.dir/src/DSP/aether_dsp_lv2.cpp.o
[ 12%] Building C object CMakeFiles/pugl.dir/extern/pugl/src/implementation.c.o
[ 18%] Building C object CMakeFiles/glad.dir/extern/glad/glad/glad.c.o
[ 25%] Building C object CMakeFiles/nanovg.dir/extern/nanovg/src/nanovg.c.o
In file included from /home/arthur/Dev/Git/Plugins/Aether/src/DSP/aether_dsp.hpp:14,
                 from /home/arthur/Dev/Git/Plugins/Aether/src/DSP/aether_dsp_lv2.cpp:16:
/home/arthur/Dev/Git/Plugins/Aether/src/DSP/utils/random.hpp:7:10: fatal error: ranges: No such file or directory
    7 | #include <ranges>
      |          ^~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/aether_dsp.dir/build.make:63: CMakeFiles/aether_dsp.dir/src/DSP/aether_dsp_lv2.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:194: CMakeFiles/aether_dsp.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 31%] Building C object CMakeFiles/pugl.dir/extern/pugl/src/x11.c.o
[ 37%] Building C object CMakeFiles/pugl.dir/extern/pugl/src/x11_gl.c.o
[ 43%] Linking C static library libpugl.a
[ 43%] Built target pugl
[ 50%] Linking C static library libglad.a
[ 50%] Built target glad
[ 56%] Linking C static library libnanovg.a
[ 56%] Built target nanovg
make: *** [Makefile:84: all] Error 2
```

**Comment by Dougal-s** [comment]
Thanks for the errors! I created a separate MacOS branch that successfully compiles although I haven't been able to verify that the plugin works. You can find the MacOS binaries as artifacts under the actions tab [here](https://github.com/Dougal-s/Aether/actions/runs/778877583).

The default c++ compiler on Pop_OS! 20.04 is g++-9, while for now Aether requires g++10 or greater. So you may want to use the binaries produced as artifacts by the automated builds under the actions tab [here](https://github.com/Dougal-s/Aether/actions/runs/761512117). You can also install a newer version of g++ through apt using `sudo apt install g++-10`. Then run cmake with the environment variable `CXX` set to `g++-10`:
```sh
CXX=g++-10 cmake .. -DCMAKE_BUILD_TYPE="Release"
```
instead of
```sh
cmake .. -DCMAKE_BUILD_TYPE="Release"
```
Hope that helps and feel free to ask if there are any more problems!

**Comment by david0** [comment]
Thanks, now its compiling fine!

Unfortunatly both my compiled binary and the github artifact creates a segfauls when run with UI (jalv.gtk and REAPER):
```
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=10, address=0x102f3c000)
    frame #0: 0x000000010d5dd544 aether_ui.so`decltype(this=0x00007ffeefbfba48, __t=0x00007ffeefbfba34, __u=0x0000000102f3c000)) + (std::__1::forward<float const&>(fp0))) std::__1::plus<void>::operator()<float&, float const&>(float&, float const&) const at functional:538:50
    frame #1: 0x000000010d5dd4e4 aether_ui.so`float std::__1::reduce<float const*, float, std::__1::plus<void> >(__first=0x0000000102f3c000, __last=0x00000001019d4470, __init=NaN, __b=plus<void> @ 0x00007ffeefbfba48) at numeric:187:18
    frame #2: 0x000000010d5dd4a7 aether_ui.so`float std::__1::reduce<float const*, float>(__first=0x00000001019d4474, __last=0x00000001019d4470, __init=0) at numeric:196:12
    frame #3: 0x000000010d5cb540 aether_ui.so`std::__1::iterator_traits<float const*>::value_type std::__1::reduce<float const*>(__first=0x00000001019d4474, __last=0x00000001019d4470) at numeric:204:12
  * frame #4: 0x000000010d5cb1fb aether_ui.so`Spectrum::draw_impl(this=0x0000000101666920) const at ui_tree.cpp:652:28
    frame #5: 0x000000010d5c42b5 aether_ui.so`UIElement::draw(this=0x0000000101666920) const at ui_tree.cpp:216:2
    frame #6: 0x000000010d555e6f aether_ui.so`Group::draw_impl(this=0x00000001016666a0) const at ui_tree.hpp:453:11
    frame #7: 0x000000010d5c42b5 aether_ui.so`UIElement::draw(this=0x00000001016666a0) const at ui_tree.cpp:216:2
    frame #8: 0x000000010d555e6f aether_ui.so`Group::draw_impl(this=0x00000001019d4310) const at ui_tree.hpp:453:11
    frame #9: 0x000000010d5c42b5 aether_ui.so`UIElement::draw(this=0x00000001019d4310) const at ui_tree.cpp:216:2
    frame #10: 0x000000010d5ce145 aether_ui.so`UITree::draw(this=0x00000001019d4300) const at ui_tree.cpp:883:9
    frame #11: 0x000000010d53ea10 aether_ui.so`Aether::UI::View::draw(this=0x00000001019d4200) at aether_ui.cpp:1179:11
    frame #12: 0x000000010d53e8d9 aether_ui.so`Aether::UI::View::onEvent(this=0x00000001019d4200, (null)=0x00007ffeefbfbe58)7, PuglEventExpose> const&) at aether_ui.cpp:1137:4
    frame #13: 0x000000010d59ec9d aether_ui.so`pugl::Status pugl::View::dispatch<Aether::UI::View>(target=0x00000001019d4200, event=0x00007ffeefbfbe58) at pugl.hpp:653:21
    frame #14: 0x000000010d59eb67 aether_ui.so`PuglStatus pugl::View::eventFunc<Aether::UI::View>(view=0x0000000101666320, event=0x00007ffeefbfbe58) at pugl.hpp:702:38
    frame #15: 0x000000010d5e1864 aether_ui.so`puglDispatchEvent [inlined] puglDispatchEventInContext(view=<unavailable>, event=<unavailable>) at implementation.c:0 [opt]
    frame #16: 0x000000010d5e17c5 aether_ui.so`puglDispatchEvent(view=0x0000000101666320, event=0x00007ffeefbfbe58) at implementation.c:418 [opt]
    frame #17: 0x000000010d5e1d28 aether_ui.so`-[PuglWrapperView dispatchExpose:](self=0x00000001016915a0, _cmd=<unavailable>, rect=(origin = (x = 0, y = 0), size = (width = 1230, height = 700))) at mac.m:224:3 [opt]
    frame #18: 0x00007fff2cfe7f4b AppKit`-[_NSOpenGLViewBackingLayer display] + 836

```

```
(lldb) frame variable
(Spectrum *) this = 0x0000000101666920
(const std::array<float, 2000> &) channel = 0x00000001019d4470: {
  __elems_ = {
    [0] = 0  
    [1] = 0  
    [2] = 0  
    [3] = 0  
    [4] = 0  
    [5] = 0  
    ...
  }
}
(const (anonymous class)) gain_to_y = {}
(size_t) i = 1
(const float) x = 0.0911927446
(size_t) ip2 = 0
(const float) band_level = 1.40129846E-45
(const float) y = 4.28983423E-38
(lldb) p this->m_bounds
(Frame) $7 = (x1 = 0, y1 = 0, x2 = 0, y2 = 0)
```

**Comment by REIS0** [comment]
@Dougal-s Didn't know there was binaries, thanks.

Unfortunately I'm still getting errors when trying to compile, tried with both `g++-10` and `clang++-10` 
```
[ 12%] Built target nanovg
[ 37%] Built target pugl
[ 50%] Built target glad
[ 56%] Building CXX object CMakeFiles/aether_ui.dir/src/UI/aether_ui.cpp.o
/home/arthur/Dev/Git/Plugins/Aether/src/UI/aether_ui.cpp:5:10: fatal error: span: No such file or directory
    5 | #include <span>
      |          ^~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/aether_ui.dir/build.make:63: CMakeFiles/aether_ui.dir/src/UI/aether_ui.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:167: CMakeFiles/aether_ui.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

**Comment by sjaehn** [comment]
@REIS0 It looks like (some of) the C++20 libraries are missing (BTW, I also had to set `CC=gcc-10`). @Dougal-s used the up-to-date version of C++. This may have some advantages and also some disadvantages. I decided for my projects to use language standards that are available on almost all users build systems (even on the LTS systems). OK, a lack of new features is a clear disadvantage of my approach. But your way of providing binaries (with statically linked libraries) is fine, too.

**Comment by REIS0** [comment]
@sjaehn not even with `CC=gcc-10` worked, but since there's already binaries I'm just nit picking. I'll be testing it soon!

**Comment by Dougal-s** [comment]
Whoops, sorry I forgot to commit some code so the spectrum had a width of 0, leading to a division by 0 causing an end pointer to appear before its start pointer.

@REIS0 the MacOS branch should fix the compilation error you were getting. The above error also affected the master branch, but instead of crashing it just displays a blank window. It should be fixed in the newest Actions run for the master branch, which you can find [here](https://github.com/Dougal-s/Aether/actions/runs/781254718).

@sjaehn Thanks! I think your method is probably preferable and in this case I should have supported at least g++9 as I didn't really make use of the newer features. Either way, at least the MacOS branch now supports g++9!

**Comment by david0** [comment]
Now the plugin UI works on mac!

 A small problems remains: The round knobs do not turn, but clearly the parameters. I. e. I can turn the "Delay" knob and the visualization of the repeats change, but still the knob is drawn as being in the middle.

**Comment by Dougal-s** [comment]
I fixed an issue where the nanovg draw calls were ordered weirdly, which could explain why the vector graphics drawn using nanovg (the knobs) weren't updating but the graphics drawn directly with OpenGL (the delay visual) were, although I'm not sure why it would only cause issues on mac. If this doesn't work, could you send a screenshot and check if the level meters function correctly?

**Comment by david0** [comment]
Unfortunately no change at all in the behaviour:
![screen3](https://user-images.githubusercontent.com/1685610/116039318-e265d200-a66a-11eb-9c7e-fda8064f6de9.gif)

**Comment by Dougal-s** [comment]
I've figured out the issue! It appears that if I try to parse a number that ends with the suffix d, it returns 0. So the string "135deg" would return 0 degrees. I'm not sure why this behavior only occurs on MacOS, but I've switched to using other angle units.

**Comment by david0** [comment]
Yes, that was it! Now the knobs are working, Thanks 👍

**Comment by Dougal-s** [comment]
Thanks for all the help!
